# Generated by Django 4.1.4 on 2022-12-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_expired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_payment.payments')),
            ],
            options={
                'db_table': 'Api-Payments_expired',
            },
        ),
    ]
