# Generated by Django 4.1.4 on 2022-12-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_payment', '0002_payments_expired'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payments',
            table='Api_Payments',
        ),
        migrations.AlterModelTable(
            name='payments_expired',
            table='Api_Payments_expired',
        ),
    ]
