# Generated by Django 4.1.4 on 2022-12-27 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_services_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_payment', '0003_alter_payments_table_alter_payments_expired_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_expired',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payments_expired',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_services.services'),
        ),
        migrations.AddField(
            model_name='payments_expired',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
