# Generated by Django 4.1.4 on 2022-12-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_alter_services_logo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='Api-Services',
        ),
    ]
