# Generated by Django 4.1.4 on 2022-12-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_alter_services_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='Api_Services',
        ),
    ]
